// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLa1Pk5U3oYf1GJZ8MZuDy49JwmodF1io',
    appId: '1:722137927084:web:4a0c21271a35a81888be09',
    messagingSenderId: '722137927084',
    projectId: 'uni-lol-verse',
    authDomain: 'uni-lol-verse.firebaseapp.com',
    storageBucket: 'uni-lol-verse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4U0hg0SuhfCnnD4EW2RnHcC2Qmge2-8U',
    appId: '1:722137927084:android:f1f1a292f06b739a88be09',
    messagingSenderId: '722137927084',
    projectId: 'uni-lol-verse',
    storageBucket: 'uni-lol-verse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODsnTIKwzJ-tJsVUjYQW_BI_1ZC-Tp-c',
    appId: '1:722137927084:ios:f39dc2e19c32977c88be09',
    messagingSenderId: '722137927084',
    projectId: 'uni-lol-verse',
    storageBucket: 'uni-lol-verse.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODsnTIKwzJ-tJsVUjYQW_BI_1ZC-Tp-c',
    appId: '1:722137927084:ios:f39dc2e19c32977c88be09',
    messagingSenderId: '722137927084',
    projectId: 'uni-lol-verse',
    storageBucket: 'uni-lol-verse.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLa1Pk5U3oYf1GJZ8MZuDy49JwmodF1io',
    appId: '1:722137927084:web:7713c4c814c27a1988be09',
    messagingSenderId: '722137927084',
    projectId: 'uni-lol-verse',
    authDomain: 'uni-lol-verse.firebaseapp.com',
    storageBucket: 'uni-lol-verse.firebasestorage.app',
  );
}
